### ISSUE TITLE
Makefile: Add support for deploying a gitea instance as a make target

### ISSUE THREAD

**Issue by LaVLaS** [opendatahub-io/ai-edge#116]
Currently the steps to deploy a gitea instance is outlined in the README (#30) but there is no controlled way to deploy it using automation.  We should move these steps to the Makefile so that we can ensure that the gitea instance is uniform and known across any deployment in all environments.

This Makefile target should also be documented as part of #110 

Expected workflow:
1. Provision Cluster
1. Run `make deploy-gitea`
1. Fork github/opendatahub-io/ai-edge -- gitea/edge-user/ai-edge
1. Update gitea/edge-user/ai-edge to point to this gitea server instance
1. Install ACM
1. Run ACM registration that points to our gitea server

- [ ] Add deployment of the gitea-operator catalogsource and subscription to a Makefile target
- [ ] Add creation of the `Gitea` custom resource as a separate target

**Comment by adelton** [comment]
As also discussed in https://github.com/opendatahub-io/ai-edge/issues/129 -- it is not clear why Gitea is needed at all, rather than optional. But if it is needed (and even if it is optional), it needs to be in place when the GitOps pipeline runs, otherwise that pipeline run won't be able to file a proper pull request to update the container image SHA-256 to the newly built and pushed one.

**Comment by adelton** [comment]
Hmm, this was closed via https://github.com/opendatahub-io/ai-edge/pull/154 but that does not touch any `Makefile` at all. 

Should this issue be kept open? Or is it closed with "current approach is good enough"?

**Comment by LaVLaS** [comment]
For the record, originally I was going to add a makefile target to deploy gitea when i created the initial PR but decided against it until we added a capability that specifically targeted or required testing against gitea.  Right now, there is a link to the gitea/README.md which I feel is sufficient for now if anyone wants to utilize gitea.
