### ISSUE TITLE
Make GitOps pipeline use the latest tested image and repo

### ISSUE THREAD

**Issue by piotrpdev** [opendatahub-io/ai-edge#125]
## Description

The current pipeline workflow requires the user to manually copy the resulting image digest of a newly tested and uploaded image from the testing pipeline:

https://github.com/opendatahub-io/ai-edge/blob/f148f63a4c4288ad917428e63f6bfeac2f5355a2/pipelines/tekton/test-mlflow-image-pipeline/test-mlflow-image-pipeline.yaml#L120-L121

to the GitOps pipeline.

https://github.com/opendatahub-io/ai-edge/blob/f148f63a4c4288ad917428e63f6bfeac2f5355a2/pipelines/tekton/gitops-update-pipeline/gitops-update-pipeline.yaml#L13-L14

The GitOps pipeline also doesn't validate the image repo, the pipeline should be modified to:

- By default, having a step in the GitOps pipeline that uses the [`openshift-client` ClusterTask](https://hub.tekton.dev/tekton/task/openshift-client) to get the latest successfully tested and uploaded image ([like so](https://github.com/opendatahub-io/ai-edge/issues/68#issuecomment-1747485029)) along with the repo to which it was uploaded, and make the PR with that.

- Optionally, allow the user to manually specify the image repo and digest so they can override the values from above.

> **Warning**
> Make sure you're getting the latest image for the **correct model**, this will require adding a `"model-name"` and `"model-version"` param to the GitOps pipeline similar to [the other pipelines](https://github.com/opendatahub-io/ai-edge/blob/f148f63a4c4288ad917428e63f6bfeac2f5355a2/pipelines/tekton/azureml-container-pipeline/azureml-container-pipeline.yaml#L7-L11).

> **Note**
> Modifying the testing pipeline to [emit the uploaded image repo and digest as a result](https://tekton.dev/docs/pipelines/pipelines/#emitting-results-from-a-pipeline) is probably a better approach than using a long and complicated `jsonpath` in the `oc` command.

Resolves #92 

## A/C
- Resulting testing pipeline data doesn't have to be copied to the GitOps pipeline params for it to work
- GitOps pipeline:
	- Uses image repo and digest from the latest successfully tested and uploaded image **(for the correct model)** by default
	- Allows the user to override the values above using the params if they want to
- All of the pipelines and the standard workflow in [pipeline/README](https://github.com/opendatahub-io/ai-edge/blob/main/pipelines/README.md) still works (can't be too safe)

**Comment by adelton** [comment]
Similar or same as https://github.com/opendatahub-io/ai-edge/issues/92 -- working on it now.
