### ISSUE TITLE
Use Elyra to execute Stefan's Tekton pipeline from a Jupyter notebook.

### ISSUE THREAD

**Issue by piotrpdev** [opendatahub-io/ai-edge#17]
### User Story
- #2 

### References
- [Elyra](https://elyra.readthedocs.io/en/latest/getting_started/overview.html)
- [Stefan's Tekton pipeline](https://github.com/opendatahub-io/ai-edge/issues/16)
- > [*"We want to make sure that the "AI' in AI at the Edge is fully supported by the ODH workflow"*](https://github.com/opendatahub-io/ai-edge/issues/2#issuecomment-1674886008)

### A/C
TBD

**Comment by israel-hdez** [comment]
FYI: #20

**Comment by piotrpdev** [comment]
#20 makes more sense.
