### ISSUE TITLE
Create the user scenarios for the demo

### ISSUE THREAD

**Issue by MyriamFentanes** [opendatahub-io/ai-edge#29]
Based on the conversations on the edge business call.

**Comment by adelton** [comment]
Can someone who was on that edge business call expand on the request?

I understand multiple demos were conducted ... so is this actually done, one way or another?

**Comment by piotrpdev** [comment]
> Can someone who was on that edge business call expand on the request?
> 
> I understand multiple demos were conducted ... so is this actually done, one way or another?

I think it is, we've done several demos and the residency is going to involve new user scenarios anyway. @LaVLaS @MyriamFentanes can we close this?

**Comment by LaVLaS** [comment]
Closing this as the demo is complete and this issue was created while we were still trying to decide the type of work to track in upstream issues
