### ISSUE TITLE
Add ACM specific setup to Repository

### ISSUE THREAD

**Issue by StevenTobin** [opendatahub-io/ai-edge#35]
Files for ACM application should also be in the repo to deploy the odh-core  and odh-edge applications in ACM.

An example of how to structure these files is [here](https://github.com/redhat-ztp/ztp-acm-manifests/tree/main).

**Comment by StevenTobin** [comment]
Closed with https://github.com/opendatahub-io/ai-edge/pull/37 right @LaVLaS  ?

**Comment by StevenTobin** [comment]
Or does https://github.com/opendatahub-io/ai-edge/pull/46 close this @grdryn ?

**Comment by LaVLaS** [comment]
Closing this as we have outlined the `near-edge` ACM setup.  The next phase of our work will be aligned with providing ODH integration with ACM for visibility of deploying and monitoring models in near edge locations
