### ISSUE TITLE
As a MLOps engineer I would like to register my model on a Quay registry so I can version it and make it available for deployment.

### ISSUE THREAD

**Issue by LaVLaS** [opendatahub-io/ai-edge#4]

**Comment by piotrpdev** [comment]
The pipeline code currently uses [`skopeo-copy`](https://hub.tekton.dev/tekton/task/skopeo-copy) and sends it to this public quay repo I made: https://quay.io/repository/rhoai-edge/bike-rentals-auto-ml

**Comment by piotrpdev** [comment]
Closed for now because above is good enough.

**Comment by devguyio** [comment]
Reopening, for this to be closed we need to have the manifests pushed and ready in the repo. Probably this can be resolved by #2
