### ISSUE TITLE
Update pipeline to use official Task from Tekton Hub once fix merged

### ISSUE THREAD

**Issue by grdryn** [opendatahub-io/ai-edge#67]
@piotrpdev submitted a fix here: [`https://github.com/tektoncd/catalog/pull/1191`](https://github.com/tektoncd/catalog/pull/1191), and we're using it in the GitOps update pipeline (see [here](https://github.com/opendatahub-io/ai-edge/pull/54#discussion_r1320156345)). Once that fix is merged and available from Tekton, we should update the pipeline to consume it from there rather than from Peter's fork.

**Comment by piotrpdev** [comment]
The PR has been merged: https://github.com/tektoncd/catalog/pull/1191#pullrequestreview-1644753800
