### ISSUE TITLE
Create a traffic generator for the housing app similar to the bike rental traffic generator app

### ISSUE THREAD

**Issue by devguyio** [opendatahub-io/ai-edge#72]
### Description
In order to simulate an inference app running in a production environment, we need a traffic generator that uses a set of test data and creates a load of a random number of requests (< 1000 requests) with an arbitrary number of parallel requests. 

One was created for the bike rental app in #61 as a CronJob using abb which can be used as a reference.

### A/C
- When the housing app is deployed, a CronJob is deployed in the same namespace that creates a Job every 5 min which generates inference requests.
- The Job creates an arbitrary number of requests in each run between 100 & 1000, with an arbitrary number of parallel requests.
- The Job uses a test dataset from which it chooses a random invocation.
- The Job is part of the ACM housing app (i.e. the manifests gets created via ACM through the GitOps workflow)
- The test dataset ConfigMap is generated via a kustomization ConfigGenerator.

**Comment by piotrpdev** [comment]
[This is where the tensorflow-housing model comes from](https://github.com/mlflow/mlflow/tree/6de2829a28898001aabcc681750d03c5cd291399/examples/tensorflow). It uses the "California Housing dataset" [[sklearn]](https://scikit-learn.org/stable/datasets/real_world.html#california-housing-dataset) [[source]](https://www.dcc.fc.up.pt/~ltorgo/Regression/cal_housing.html).
